title: Justin Duckett
logo: assets/headshot circle.jpg
description_line1: Analytics Lead, Government of Ontario
description_line2: Analytics Engineering | dbt, BigQuery, SQL, Python
#show_downloads: true
theme: jekyll-theme-minimal
